/*
 * generated by Xtext
 */
package com.laegler.fastbpmn.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

import com.laegler.fastbpmn.services.FastBpmnGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an
 * example
 */
public class FastBpmnFormatter extends AbstractDeclarativeFormatter {

	@Override
	protected void configureFormatting(FormattingConfig c) {
		FastBpmnGrammarAccess ga = (FastBpmnGrammarAccess) getGrammarAccess();
		
		// TODO
//		c.setLinewrap().before(ga.getFDefinitionsAccess().getRootElementsAssignment_5());
//		c.setLinewrap().before(ga.getFProcessAccess().getFlowNodesAssignment_3());
//		c.setLinewrap().before(ga.getFGatewayAccess().getOptionsAssignment_5());
//		c.setLinewrap().before(ga.getFOptionAccess().getFlowNodesAssignment_5());
		
//		c.setLinewrap().before(ga.getFFlowNodeAccess().getRule());
		
//		c.setLinewrap().before(ga.getFDefinitionsAccess().getEndKeyword_7());
//		c.setLinewrap().before(ga.getFProcessAccess().getEndKeyword_5());
//		c.setLinewrap().before(ga.getFGatewayAccess().getEndKeyword_6());
//		c.setLinewrap().after(ga.getFOptionAccess().getFlowNodesAssignment_5());
		
//		c.setIndentationIncrement().before(ga.getFDefinitionsAccess().getRootElementsAssignment_5());
//		c.setIndentationIncrement().before(ga.getFProcessAccess().getFlowNodesFFlowNodeParserRuleCall_3_0());
//		c.setIndentationIncrement().before(ga.getFGatewayAccess().getOptionsAssignment_5());
//		c.setIndentationIncrement().before(ga.getFOptionAccess().getFlowNodesAssignment_5());
		
//		c.setIndentationDecrement().before(ga.getFDefinitionsAccess().getEndKeyword_7());
//		c.setIndentationDecrement().before(ga.getFProcessAccess().getEndKeyword_5());
//		c.setIndentationDecrement().before(ga.getFGatewayAccess().getEndKeyword_6());
//		c.setIndentationDecrement().after(ga.getFOptionAccess().getFlowNodesAssignment_5());
	}

}
