/*
* generated by Xtext
*/
package com.laegler.fastbpmn.ui.contentassist;

import com.laegler.fastbpmn.ui.contentassist.AbstractFastBpmnProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FastBpmnProposalProvider extends AbstractFastBpmnProposalProvider {

}
