/*
 * generated by Xtext
 */
package com.laegler.fastbpmn;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FastBpmnRuntimeModule extends com.laegler.fastbpmn.AbstractFastBpmnRuntimeModule {

}
