/*
 * generated by Xtext
 */
package com.laegler.fastbpmn.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class FastBpmnScopeProvider extends AbstractDeclarativeScopeProvider {

	// IScope scope_Process_participant(Root root, EReference ref) {
	// return Scopes.scopeFor(root.getParticipants());
	// }
	// IScope scope_Lane_participant(Root root, EReference ref) {
	// return Scopes.scopeFor(root.getParticipants());
	// }
	// IScope scope_Message_target(Process process, EReference ref) {
	// return Scopes.scopeFor(process.getNodes());
	// }
	// IScope scope_Data_target(Process process, EReference ref) {
	// return Scopes.scopeFor(process.getNodes());
	// }

}
