/*
* generated by Xtext
*/
package com.laegler.fastbpmn.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FastBpmnOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
