/*
 * generated by Xtext
 */
package com.laegler.fastbpmn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FastBpmnUiModule extends com.laegler.fastbpmn.ui.AbstractFastBpmnUiModule {
	public FastBpmnUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
